/****************************************************
Hero header file, containts the definition
of a hero class

Last modified: 11/3/2013

******************************************************/

#ifndef _HERO_H
#define _HERO_H

#include "entity.h"

namespace heroNS{
	//assign frame numbers here
	enum {
		HERO_FACING_UP, 
		HERO_FACING_DOWN,  
		HERO_FACING_LEFT,  
		HERO_FACING_RIGHT,
		HERO_FACING_UP_RIGHT, 
		HERO_FACING_UP_LEFT,
		HERO_FACING_DOWN_RIGHT,
		HERO_FACING_DOWN_LEFT,

		HERO_WALKING_UP_START,
		HERO_WALKING_UP_END,
		HERO_WALKING_DOWN_START,
		HERO_WALKING_DOWN_END,
		HERO_WALKING_LEFT_START,
		HERO_WALKING_LEFT_END,
		HERO_WALKING_RIGHT_START,
		HERO_WALKING_RIGHT_END,

		HERO_WALKING_UP_RIGHT_START,
		HERO_WALKING_UP_RIGHT_END,
		HERO_WALKING_UP_LEFT_START,
		HERO_WALKING_UP_LEFT_END,
		HERO_WALKING_DOWN_RIGHT_START,
		HERO_WALKING_DOWN_RIGHT_END,
		HERO_WALKING_DOWN_LEFT_START,
		HERO_WALKING_DOWN_LEFT_END,

		HERO_SWINGING_UP_START,
		HERO_SWINGING_UP_END,
		HERO_SWINGING_DOWN_START,
		HERO_SWINGING_DOWN_END,
		HERO_SWINGING_LEFT_START,
		HERO_SWINGING_LEFT_END,
		HERO_SWINGING_RIGHT_START,
		HERO_SWINGING_RIGHT_END,

		HERO_SWINGING_UP_RIGHT_START,
		HERO_SWINGING_UP_RIGHT_END,
		HERO_SWINGING_UP_LEFT_START,
		HERO_SWINGING_UP_LEFT_END,
		HERO_SWINGING_DOWN_RIGHT_START,
		HERO_SWINGING_DOWN_RIGHT_END,
		HERO_SWINGING_DOWN_LEFT_START,
		HERO_SWINGING_DOWN_LEFT_END
	};
}

class Hero: public Entity
{
public:
	void attack(DIR);
	void move(DIR);

	virtual void draw();	
	virtual void update();	
	virtual void act();

	DIR getDirectionFacing(){return facing;}

private:
	DIR facing;

};

#endif
